import React, { createContext, useContext, useState, useEffect } from "react";
import axios from "axios";
import { API_BASE } from "../api/authApi";

// Create Context
const InquiryContext = createContext();

// Hook for easy usage
export const useInquiries = () => useContext(InquiryContext);

export const InquiryProvider = ({ children }) => {
  const [inquiries, setInquiries] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  // 🔹 Fetch inquiries from backend
  const fetchInquiries = async () => {
    setLoading(true);
    setError("");
    try {
      const response = await axios.get(
        `${API_BASE}/api/inquiryRoutes/getInquiries`
      );

      console.log({ response: response.data.data });
      const inquiries = [
        {
          id: "Inq-2",
          qty: 11,
          customer: "Customer Name with longer text that may overflow (2)",
          broker: null,
          sales: "Sales Person (2)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A2",
              qty: 21,
              rate: 101,
              grade: 2,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 96,
            },
            {
              id: 2,
              name: "Item B2",
              qty: 16,
              rate: 121,
              grade: 2,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 111,
            },
          ],
        },
        {
          id: "Inq-3",
          qty: 12,
          customer: "Customer Name with longer text that may overflow (3)",
          broker: "Broker Name with longer text too (3)",
          sales: "Sales Person (3)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A3",
              qty: 22,
              rate: 102,
              grade: 3,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 97,
            },
            {
              id: 2,
              name: "Item B3",
              qty: 17,
              rate: 122,
              grade: 3,
              winding: 25,
              pq: "Yes",
              clq: "No",
              lastRate: 112,
            },
          ],
        },
        {
          id: "Inq-4",
          qty: 13,
          customer: "Customer Name with longer text that may overflow (4)",
          broker: null,
          sales: "Sales Person (4)",
          status: "High Priority",
          items: [
            {
              id: 1,
              name: "Item A4",
              qty: 23,
              rate: 103,
              grade: 4,
              winding: 10,
              pq: "No",
              clq: "Yes",
              lastRate: 98,
            },
            {
              id: 2,
              name: "Item B4",
              qty: 18,
              rate: 123,
              grade: 4,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 113,
            },
          ],
        },
        {
          id: "Inq-5",
          qty: 14,
          customer: "Customer Name with longer text that may overflow (5)",
          broker: "Broker Name with longer text too (5)",
          sales: "Sales Person (5)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A5",
              qty: 24,
              rate: 104,
              grade: 5,
              winding: 15,
              pq: "Yes",
              clq: "No",
              lastRate: 99,
            },
            {
              id: 2,
              name: "Item B5",
              qty: 19,
              rate: 124,
              grade: 5,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 114,
            },
          ],
        },
        {
          id: "Inq-6",
          qty: 15,
          customer: "Customer Name with longer text that may overflow (6)",
          broker: null,
          sales: "Sales Person (6)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A6",
              qty: 25,
              rate: 105,
              grade: 1,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 100,
            },
            {
              id: 2,
              name: "Item B6",
              qty: 20,
              rate: 125,
              grade: 1,
              winding: 25,
              pq: "No",
              clq: "Yes",
              lastRate: 115,
            },
          ],
        },
        {
          id: "Inq-7",
          qty: 16,
          customer: "Customer Name with longer text that may overflow (7)",
          broker: "Broker Name with longer text too (7)",
          sales: "Sales Person (7)",
          status: "High Priority",
          items: [
            {
              id: 1,
              name: "Item A7",
              qty: 26,
              rate: 106,
              grade: 2,
              winding: 10,
              pq: "Yes",
              clq: "No",
              lastRate: 101,
            },
            {
              id: 2,
              name: "Item B7",
              qty: 21,
              rate: 126,
              grade: 2,
              winding: 15,
              pq: "Yes",
              clq: "No",
              lastRate: 116,
            },
          ],
        },
        {
          id: "Inq-8",
          qty: 17,
          customer: "Customer Name with longer text that may overflow (8)",
          broker: null,
          sales: "Sales Person (8)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A8",
              qty: 27,
              rate: 107,
              grade: 3,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 102,
            },
            {
              id: 2,
              name: "Item B8",
              qty: 22,
              rate: 127,
              grade: 3,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 117,
            },
          ],
        },
        {
          id: "Inq-9",
          qty: 18,
          customer: "Customer Name with longer text that may overflow (9)",
          broker: "Broker Name with longer text too (9)",
          sales: "Sales Person (9)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A9",
              qty: 28,
              rate: 108,
              grade: 4,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 103,
            },
            {
              id: 2,
              name: "Item B9",
              qty: 23,
              rate: 128,
              grade: 4,
              winding: 25,
              pq: "Yes",
              clq: "No",
              lastRate: 118,
            },
          ],
        },
        {
          id: "Inq-10",
          qty: 19,
          customer: "Customer Name with longer text that may overflow (10)",
          broker: null,
          sales: "Sales Person (10)",
          status: "High Priority",
          items: [
            {
              id: 1,
              name: "Item A10",
              qty: 29,
              rate: 109,
              grade: 5,
              winding: 10,
              pq: "No",
              clq: "Yes",
              lastRate: 104,
            },
            {
              id: 2,
              name: "Item B10",
              qty: 24,
              rate: 129,
              grade: 5,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 119,
            },
          ],
        },
        {
          id: "Inq-11",
          qty: 20,
          customer: "Customer Name with longer text that may overflow (11)",
          broker: "Broker Name with longer text too (11)",
          sales: "Sales Person (11)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A11",
              qty: 30,
              rate: 110,
              grade: 1,
              winding: 15,
              pq: "Yes",
              clq: "No",
              lastRate: 105,
            },
            {
              id: 2,
              name: "Item B11",
              qty: 25,
              rate: 130,
              grade: 1,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 120,
            },
          ],
        },
        {
          id: "Inq-12",
          qty: 21,
          customer: "Customer Name with longer text that may overflow (12)",
          broker: null,
          sales: "Sales Person (12)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A12",
              qty: 31,
              rate: 111,
              grade: 2,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 106,
            },
            {
              id: 2,
              name: "Item B12",
              qty: 26,
              rate: 131,
              grade: 2,
              winding: 25,
              pq: "No",
              clq: "Yes",
              lastRate: 121,
            },
          ],
        },
        {
          id: "Inq-13",
          qty: 22,
          customer: "Customer Name with longer text that may overflow (13)",
          broker: "Broker Name with longer text too (13)",
          sales: "Sales Person (13)",
          status: "High Priority",
          items: [
            {
              id: 1,
              name: "Item A13",
              qty: 32,
              rate: 112,
              grade: 3,
              winding: 10,
              pq: "Yes",
              clq: "No",
              lastRate: 107,
            },
            {
              id: 2,
              name: "Item B13",
              qty: 27,
              rate: 132,
              grade: 3,
              winding: 15,
              pq: "Yes",
              clq: "No",
              lastRate: 122,
            },
          ],
        },
        {
          id: "Inq-14",
          qty: 23,
          customer: "Customer Name with longer text that may overflow (14)",
          broker: null,
          sales: "Sales Person (14)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A14",
              qty: 33,
              rate: 113,
              grade: 4,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 108,
            },
            {
              id: 2,
              name: "Item B14",
              qty: 28,
              rate: 133,
              grade: 4,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 123,
            },
          ],
        },
        {
          id: "Inq-15",
          qty: 24,
          customer: "Customer Name with longer text that may overflow (15)",
          broker: "Broker Name with longer text too (15)",
          sales: "Sales Person (15)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A15",
              qty: 34,
              rate: 114,
              grade: 5,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 109,
            },
            {
              id: 2,
              name: "Item B15",
              qty: 29,
              rate: 134,
              grade: 5,
              winding: 25,
              pq: "Yes",
              clq: "No",
              lastRate: 124,
            },
          ],
        },
        {
          id: "Inq-16",
          qty: 25,
          customer: "Customer Name with longer text that may overflow (16)",
          broker: null,
          sales: "Sales Person (16)",
          status: "High Priority",
          items: [
            {
              id: 1,
              name: "Item A16",
              qty: 35,
              rate: 115,
              grade: 1,
              winding: 10,
              pq: "No",
              clq: "Yes",
              lastRate: 110,
            },
            {
              id: 2,
              name: "Item B16",
              qty: 30,
              rate: 135,
              grade: 1,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 125,
            },
          ],
        },
        {
          id: "Inq-17",
          qty: 26,
          customer: "Customer Name with longer text that may overflow (17)",
          broker: "Broker Name with longer text too (17)",
          sales: "Sales Person (17)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A17",
              qty: 36,
              rate: 116,
              grade: 2,
              winding: 15,
              pq: "Yes",
              clq: "No",
              lastRate: 111,
            },
            {
              id: 2,
              name: "Item B17",
              qty: 31,
              rate: 136,
              grade: 2,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 126,
            },
          ],
        },
        {
          id: "Inq-18",
          qty: 27,
          customer: "Customer Name with longer text that may overflow (18)",
          broker: null,
          sales: "Sales Person (18)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A18",
              qty: 37,
              rate: 117,
              grade: 3,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 112,
            },
            {
              id: 2,
              name: "Item B18",
              qty: 32,
              rate: 137,
              grade: 3,
              winding: 25,
              pq: "No",
              clq: "Yes",
              lastRate: 127,
            },
          ],
        },
        {
          id: "Inq-19",
          qty: 28,
          customer: "Customer Name with longer text that may overflow (19)",
          broker: "Broker Name with longer text too (19)",
          sales: "Sales Person (19)",
          status: "High Priority",
          items: [
            {
              id: 1,
              name: "Item A19",
              qty: 38,
              rate: 118,
              grade: 4,
              winding: 10,
              pq: "Yes",
              clq: "No",
              lastRate: 113,
            },
            {
              id: 2,
              name: "Item B19",
              qty: 33,
              rate: 138,
              grade: 4,
              winding: 15,
              pq: "Yes",
              clq: "No",
              lastRate: 128,
            },
          ],
        },
        {
          id: "Inq-20",
          qty: 29,
          customer: "Customer Name with longer text that may overflow (20)",
          broker: null,
          sales: "Sales Person (20)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A20",
              qty: 39,
              rate: 119,
              grade: 5,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 114,
            },
            {
              id: 2,
              name: "Item B20",
              qty: 34,
              rate: 139,
              grade: 5,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 129,
            },
          ],
        },
        {
          id: "Inq-21",
          qty: 30,
          customer: "Customer Name with longer text that may overflow (21)",
          broker: "Broker Name with longer text too (21)",
          sales: "Sales Person (21)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A21",
              qty: 40,
              rate: 120,
              grade: 1,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 115,
            },
            {
              id: 2,
              name: "Item B21",
              qty: 35,
              rate: 140,
              grade: 1,
              winding: 25,
              pq: "Yes",
              clq: "No",
              lastRate: 130,
            },
          ],
        },
        {
          id: "Inq-22",
          qty: 31,
          customer: "Customer Name with longer text that may overflow (22)",
          broker: null,
          sales: "Sales Person (22)",
          status: "High Priority",
          items: [
            {
              id: 1,
              name: "Item A22",
              qty: 41,
              rate: 121,
              grade: 2,
              winding: 10,
              pq: "No",
              clq: "Yes",
              lastRate: 116,
            },
            {
              id: 2,
              name: "Item B22",
              qty: 36,
              rate: 141,
              grade: 2,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 131,
            },
          ],
        },
        {
          id: "Inq-23",
          qty: 32,
          customer: "Customer Name with longer text that may overflow (23)",
          broker: "Broker Name with longer text too (23)",
          sales: "Sales Person (23)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A23",
              qty: 42,
              rate: 122,
              grade: 3,
              winding: 15,
              pq: "Yes",
              clq: "No",
              lastRate: 117,
            },
            {
              id: 2,
              name: "Item B23",
              qty: 37,
              rate: 142,
              grade: 3,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 132,
            },
          ],
        },
        {
          id: "Inq-24",
          qty: 33,
          customer: "Customer Name with longer text that may overflow (24)",
          broker: null,
          sales: "Sales Person (24)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A24",
              qty: 43,
              rate: 123,
              grade: 4,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 118,
            },
            {
              id: 2,
              name: "Item B24",
              qty: 38,
              rate: 143,
              grade: 4,
              winding: 25,
              pq: "No",
              clq: "Yes",
              lastRate: 133,
            },
          ],
        },
        {
          id: "Inq-25",
          qty: 34,
          customer: "Customer Name with longer text that may overflow (25)",
          broker: "Broker Name with longer text too (25)",
          sales: "Sales Person (25)",
          status: "High Priority",
          items: [
            {
              id: 1,
              name: "Item A25",
              qty: 44,
              rate: 124,
              grade: 5,
              winding: 10,
              pq: "Yes",
              clq: "No",
              lastRate: 119,
            },
            {
              id: 2,
              name: "Item B25",
              qty: 39,
              rate: 144,
              grade: 5,
              winding: 15,
              pq: "Yes",
              clq: "No",
              lastRate: 134,
            },
          ],
        },
        {
          id: "Inq-26",
          qty: 35,
          customer: "Customer Name with longer text that may overflow (26)",
          broker: null,
          sales: "Sales Person (26)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A26",
              qty: 45,
              rate: 125,
              grade: 1,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 120,
            },
            {
              id: 2,
              name: "Item B26",
              qty: 40,
              rate: 145,
              grade: 1,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 135,
            },
          ],
        },
        {
          id: "Inq-27",
          qty: 36,
          customer: "Customer Name with longer text that may overflow (27)",
          broker: "Broker Name with longer text too (27)",
          sales: "Sales Person (27)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A27",
              qty: 46,
              rate: 126,
              grade: 2,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 121,
            },
            {
              id: 2,
              name: "Item B27",
              qty: 41,
              rate: 146,
              grade: 2,
              winding: 25,
              pq: "Yes",
              clq: "No",
              lastRate: 136,
            },
          ],
        },
        {
          id: "Inq-28",
          qty: 37,
          customer: "Customer Name with longer text that may overflow (28)",
          broker: null,
          sales: "Sales Person (28)",
          status: "High Priority",
          items: [
            {
              id: 1,
              name: "Item A28",
              qty: 47,
              rate: 127,
              grade: 3,
              winding: 10,
              pq: "No",
              clq: "Yes",
              lastRate: 122,
            },
            {
              id: 2,
              name: "Item B28",
              qty: 42,
              rate: 147,
              grade: 3,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 137,
            },
          ],
        },
        {
          id: "Inq-29",
          qty: 38,
          customer: "Customer Name with longer text that may overflow (29)",
          broker: "Broker Name with longer text too (29)",
          sales: "Sales Person (29)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A29",
              qty: 48,
              rate: 128,
              grade: 4,
              winding: 15,
              pq: "Yes",
              clq: "No",
              lastRate: 123,
            },
            {
              id: 2,
              name: "Item B29",
              qty: 43,
              rate: 148,
              grade: 4,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 138,
            },
          ],
        },
        {
          id: "Inq-30",
          qty: 39,
          customer: "Customer Name with longer text that may overflow (30)",
          broker: null,
          sales: "Sales Person (30)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A30",
              qty: 49,
              rate: 129,
              grade: 5,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 124,
            },
            {
              id: 2,
              name: "Item B30",
              qty: 44,
              rate: 149,
              grade: 5,
              winding: 25,
              pq: "No",
              clq: "Yes",
              lastRate: 139,
            },
          ],
        },
        {
          id: "Inq-31",
          qty: 40,
          customer: "Customer Name with longer text that may overflow (31)",
          broker: "Broker Name with longer text too (31)",
          sales: "Sales Person (31)",
          status: "High Priority",
          items: [
            {
              id: 1,
              name: "Item A31",
              qty: 50,
              rate: 130,
              grade: 1,
              winding: 10,
              pq: "Yes",
              clq: "No",
              lastRate: 125,
            },
            {
              id: 2,
              name: "Item B31",
              qty: 45,
              rate: 150,
              grade: 1,
              winding: 15,
              pq: "Yes",
              clq: "No",
              lastRate: 140,
            },
          ],
        },
        {
          id: "Inq-32",
          qty: 41,
          customer: "Customer Name with longer text that may overflow (32)",
          broker: null,
          sales: "Sales Person (32)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A32",
              qty: 51,
              rate: 131,
              grade: 2,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 126,
            },
            {
              id: 2,
              name: "Item B32",
              qty: 46,
              rate: 151,
              grade: 2,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 141,
            },
          ],
        },
        {
          id: "Inq-33",
          qty: 42,
          customer: "Customer Name with longer text that may overflow (33)",
          broker: "Broker Name with longer text too (33)",
          sales: "Sales Person (33)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A33",
              qty: 52,
              rate: 132,
              grade: 3,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 127,
            },
            {
              id: 2,
              name: "Item B33",
              qty: 47,
              rate: 152,
              grade: 3,
              winding: 25,
              pq: "Yes",
              clq: "No",
              lastRate: 142,
            },
          ],
        },
        {
          id: "Inq-34",
          qty: 43,
          customer: "Customer Name with longer text that may overflow (34)",
          broker: null,
          sales: "Sales Person (34)",
          status: "High Priority",
          items: [
            {
              id: 1,
              name: "Item A34",
              qty: 53,
              rate: 133,
              grade: 4,
              winding: 10,
              pq: "No",
              clq: "Yes",
              lastRate: 128,
            },
            {
              id: 2,
              name: "Item B34",
              qty: 48,
              rate: 153,
              grade: 4,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 143,
            },
          ],
        },
        {
          id: "Inq-35",
          qty: 44,
          customer: "Customer Name with longer text that may overflow (35)",
          broker: "Broker Name with longer text too (35)",
          sales: "Sales Person (35)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A35",
              qty: 54,
              rate: 134,
              grade: 5,
              winding: 15,
              pq: "Yes",
              clq: "No",
              lastRate: 129,
            },
            {
              id: 2,
              name: "Item B35",
              qty: 49,
              rate: 154,
              grade: 5,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 144,
            },
          ],
        },
        {
          id: "Inq-36",
          qty: 45,
          customer: "Customer Name with longer text that may overflow (36)",
          broker: null,
          sales: "Sales Person (36)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A36",
              qty: 55,
              rate: 135,
              grade: 1,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 130,
            },
            {
              id: 2,
              name: "Item B36",
              qty: 50,
              rate: 155,
              grade: 1,
              winding: 25,
              pq: "No",
              clq: "Yes",
              lastRate: 145,
            },
          ],
        },
        {
          id: "Inq-37",
          qty: 46,
          customer: "Customer Name with longer text that may overflow (37)",
          broker: "Broker Name with longer text too (37)",
          sales: "Sales Person (37)",
          status: "High Priority",
          items: [
            {
              id: 1,
              name: "Item A37",
              qty: 56,
              rate: 136,
              grade: 2,
              winding: 10,
              pq: "Yes",
              clq: "No",
              lastRate: 131,
            },
            {
              id: 2,
              name: "Item B37",
              qty: 51,
              rate: 156,
              grade: 2,
              winding: 15,
              pq: "Yes",
              clq: "No",
              lastRate: 146,
            },
          ],
        },
        {
          id: "Inq-38",
          qty: 47,
          customer: "Customer Name with longer text that may overflow (38)",
          broker: null,
          sales: "Sales Person (38)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A38",
              qty: 57,
              rate: 137,
              grade: 3,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 132,
            },
            {
              id: 2,
              name: "Item B38",
              qty: 52,
              rate: 157,
              grade: 3,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 147,
            },
          ],
        },
        {
          id: "Inq-39",
          qty: 48,
          customer: "Customer Name with longer text that may overflow (39)",
          broker: "Broker Name with longer text too (39)",
          sales: "Sales Person (39)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A39",
              qty: 58,
              rate: 138,
              grade: 4,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 133,
            },
            {
              id: 2,
              name: "Item B39",
              qty: 53,
              rate: 158,
              grade: 4,
              winding: 25,
              pq: "Yes",
              clq: "No",
              lastRate: 148,
            },
          ],
        },
        {
          id: "Inq-40",
          qty: 49,
          customer: "Customer Name with longer text that may overflow (40)",
          broker: null,
          sales: "Sales Person (40)",
          status: "High Priority",
          items: [
            {
              id: 1,
              name: "Item A40",
              qty: 59,
              rate: 139,
              grade: 5,
              winding: 10,
              pq: "No",
              clq: "Yes",
              lastRate: 134,
            },
            {
              id: 2,
              name: "Item B40",
              qty: 54,
              rate: 159,
              grade: 5,
              winding: 15,
              pq: "No",
              clq: "Yes",
              lastRate: 149,
            },
          ],
        },
        {
          id: "Inq-41",
          qty: 50,
          customer: "Customer Name with longer text that may overflow (41)",
          broker: "Broker Name with longer text too (41)",
          sales: "Sales Person (41)",
          status: "Pending",
          items: [
            {
              id: 1,
              name: "Item A41",
              qty: 60,
              rate: 140,
              grade: 1,
              winding: 15,
              pq: "Yes",
              clq: "No",
              lastRate: 135,
            },
            {
              id: 2,
              name: "Item B41",
              qty: 55,
              rate: 160,
              grade: 1,
              winding: 20,
              pq: "Yes",
              clq: "No",
              lastRate: 150,
            },
          ],
        },
        {
          id: "Inq-42",
          qty: 51,
          customer: "Customer Name with longer text that may overflow (42)",
          broker: null,
          sales: "Sales Person (42)",
          status: "Normal",
          items: [
            {
              id: 1,
              name: "Item A42",
              qty: 61,
              rate: 141,
              grade: 2,
              winding: 20,
              pq: "No",
              clq: "Yes",
              lastRate: 136,
            },
            {
              id: 2,
              name: "Item B42",
              qty: 56,
              rate: 161,
              grade: 2,
              winding: 25,
              pq: "No",
              clq: "Yes",
              lastRate: 151,
            },
          ],
        },
      ];
      setInquiries(response.data.data || inquiries); // because your controller sends { success, total, data }
    } catch (err) {
      console.error("Fetch Inquiries Error:", err.message);
      setError("Failed to load inquiries");
    } finally {
      setLoading(false);
    }
  };

  // Auto-fetch when context mounts
  useEffect(() => {
    fetchInquiries();
  }, []);

  return (
    <InquiryContext.Provider
      value={{ inquiries, loading, error, fetchInquiries }}
    >
      {children}
    </InquiryContext.Provider>
  );
};
